/* 
 * DO NOT EDIT
 *
 * This file is autogenerated by molochmagic.pl.
 */
#include "moloch.h"


void molochmagic_load() {
// FILE: molochmagic.pl
  moloch_parsers_molochmagic_add(0, (uint8_t *)"PK\003\004", sizeof "PK\003\004" - 1, "application/zip");
// FILE: /Users/awick/file-5.29/magic/Magdir/adventure
    // MISSING COMPLEX: application/x-zmachine
    // MISSING COMPLEX: application/x-glulx
    // MISSING COMPLEX: application/x-tads
    // MISSING COMPLEX: application/x-tads
    // MISSING COMPLEX: application/x-tads
    // MISSING COMPLEX: application/x-tads
    // MISSING COMPLEX: application/x-t3vm-image
    // MISSING COMPLEX: application/x-adrift
// FILE: /Users/awick/file-5.29/magic/Magdir/algol68
    moloch_parsers_molochmagic_add_search((uint8_t *)"(input,", sizeof "(input," - 1, "text/x-Algol68");
    // MISSING COMMAND: regex text/x-Algol68
    // MISSING COMMAND: regex text/x-Algol68
    // MISSING COMMAND: regex text/x-Algol68
    // MISSING COMMAND: regex text/x-Algol68
// FILE: /Users/awick/file-5.29/magic/Magdir/animation
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MOVI", sizeof "MOVI" - 1, "video/x-sgi-movie");
    moloch_parsers_molochmagic_add(4, (uint8_t *)"moov", sizeof "moov" - 1, "video/quicktime");
    moloch_parsers_molochmagic_add(4, (uint8_t *)"mdat", sizeof "mdat" - 1, "video/quicktime");
    moloch_parsers_molochmagic_add(4, (uint8_t *)"idsc", sizeof "idsc" - 1, "image/x-quicktime");
    moloch_parsers_molochmagic_add(4, (uint8_t *)"pckg", sizeof "pckg" - 1, "application/x-quicktime-player");
    moloch_parsers_molochmagic_add(4, (uint8_t *)"jP", sizeof "jP" - 1, "image/jp2");
    // MISSING COMPLEX: video/3gpp2
    // MISSING COMPLEX: video/3gpp
    // MISSING COMPLEX: video/3gpp
    // MISSING COMPLEX: video/3gpp
    // MISSING COMPLEX: video/3gpp
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/quicktime
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/vnd.dvb.file
    // MISSING COMPLEX: video/vnd.dvb.file
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: audio/mp4
    // MISSING COMPLEX: audio/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: image/jp2
    // MISSING COMPLEX: image/jp2
    // MISSING COMPLEX: image/jpm
    // MISSING COMPLEX: image/jpx
    // MISSING COMPLEX: video/3gpp2
    // MISSING COMPLEX: audio/x-m4a
    // MISSING COMPLEX: audio/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/x-m4v
    // MISSING COMPLEX: video/x-m4v
    // MISSING COMPLEX: video/x-m4v
    // MISSING COMPLEX: video/mj2
    // MISSING COMPLEX: video/mj2
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/quicktime
    // MISSING COMPLEX: audio/mp4
    // MISSING COMPLEX: audio/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/mp4
    // MISSING COMPLEX: video/quicktime
    // MISSING COMPLEX: video/mpeg
    // MISSING COMPLEX: video/mpeg4-generic
    // MISSING COMPLEX: video/mpeg4-generic
    // MISSING COMPLEX: video/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMPLEX: audio/mpeg
    // MISSING COMMAND: beshort&0xFFFE audio/mpeg
    // MISSING COMMAND: beshort&0xFFFE audio/mpeg
    // MISSING COMMAND: beshort&0xFFFE audio/mpeg
    // MISSING COMMAND: beshort&0xFFFE audio/mpeg
    // MISSING COMMAND: beshort&0xFFFE audio/mpeg
    moloch_parsers_molochmagic_add(0, (uint8_t *)"ADIF", sizeof "ADIF" - 1, "audio/x-hx-aac-adif");
    // MISSING COMMAND: beshort&0xFFF6 audio/x-hx-aac-adts
    // MISSING COMMAND: beshort&0xFFE0 audio/x-mp4a-latm
    // MISSING COMPLEX: video/x-fli
    // MISSING COMPLEX: video/x-flc
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x30\x26\xb2\x75", 4, "video/x-ms-asf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\212MNG", sizeof "\212MNG" - 1, "video/x-mng");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\213JNG", sizeof "\213JNG" - 1, "video/x-jng");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#VRML V1.0 ascii", sizeof "#VRML V1.0 ascii" - 1, "model/vrml");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#VRML V2.0 utf8", sizeof "#VRML V2.0 utf8" - 1, "model/vrml");
    // MISSING COMPLEX: model/x3d
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\006\016\053\064\002\005\001\001\015\001\002\001\001\002", sizeof "\006\016\053\064\002\005\001\001\015\001\002\001\001\002" - 1, "application/mxf");
// FILE: /Users/awick/file-5.29/magic/Magdir/apple
    // MISSING COMPLEX: application/x-appleworks3
    // MISSING COMPLEX: application/x-apple-diskimage
// FILE: /Users/awick/file-5.29/magic/Magdir/archive
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xc7\x71", 2, "application/x-cpio");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x71\xc7", 2, "application/x-cpio");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<ar>", sizeof "<ar>" - 1, "application/x-archive");
    // MISSING COMPLEX: application/vnd.debian.binary-package
    // MISSING COMPLEX: application/vnd.debian.binary-package
    moloch_parsers_molochmagic_add(0, (uint8_t *)"!<arch>\n__________E", sizeof "!<arch>\n__________E" - 1, "application/x-archive");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"!<arch>", sizeof "!<arch>" - 1, "application/x-archive");
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    // MISSING COMMAND: lelong&0x8080ffff application/x-arc
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x60\xea", 2, "application/x-arj");
    // MISSING COMPLEX: application/x-lzh-compressed
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Rar!\032\7\0", sizeof "Rar!\032\7\0" - 1, "application/x-rar");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Rar!\032\7\1\0", sizeof "Rar!\032\7\1\0" - 1, "application/x-rar");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"RE\176\136", sizeof "RE\176\136" - 1, "application/x-rar");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"PK\007\010PK\003\004", sizeof "PK\007\010PK\003\004" - 1, "application/zip1");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"PK\005\006", sizeof "PK\005\006" - 1, "application/zip2");
    // MISSING COMPLEX: application/vnd.oasis.opendocument.text
    // MISSING COMPLEX: application/vnd.oasis.opendocument.text-template
    // MISSING COMPLEX: application/vnd.oasis.opendocument.text-web
    // MISSING COMPLEX: application/vnd.oasis.opendocument.text-master
    // MISSING COMPLEX: application/vnd.oasis.opendocument.graphics
    // MISSING COMPLEX: application/vnd.oasis.opendocument.graphics-template
    // MISSING COMPLEX: application/vnd.oasis.opendocument.presentation
    // MISSING COMPLEX: application/vnd.oasis.opendocument.presentation-template
    // MISSING COMPLEX: application/vnd.oasis.opendocument.spreadsheet
    // MISSING COMPLEX: application/vnd.oasis.opendocument.spreadsheet-template
    // MISSING COMPLEX: application/vnd.oasis.opendocument.chart
    // MISSING COMPLEX: application/vnd.oasis.opendocument.chart-template
    // MISSING COMPLEX: application/vnd.oasis.opendocument.formula
    // MISSING COMPLEX: application/vnd.oasis.opendocument.formula-template
    // MISSING COMPLEX: application/vnd.oasis.opendocument.database
    // MISSING COMPLEX: application/vnd.oasis.opendocument.image
    // MISSING COMPLEX: application/vnd.oasis.opendocument.image-template
    // MISSING COMPLEX: application/epub+zip
    // MISSING COMPLEX: application/zip3
    // MISSING COMPLEX: application/zip4
    // MISSING COMPLEX: application/java-archive
    // MISSING COMPLEX: application/x-ios-app
    // MISSING COMPLEX: application/zip5
    moloch_parsers_molochmagic_add(20, (uint8_t *)"\xdc\xa7\xc4\xfd", 4, "application/x-zoo");
    moloch_parsers_molochmagic_add(10, (uint8_t *)"# This is a shell archive", sizeof "# This is a shell archive" - 1, "application/octet-stream");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"d8:announce", sizeof "d8:announce" - 1, "application/x-bittorrent");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"d13:announce-list", sizeof "d13:announce-list" - 1, "application/x-bittorrent");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x1e\xe7\xff\x00", 4, "application/x-eet");
    moloch_parsers_molochmagic_add(8, (uint8_t *)"\x19\x04\x00\x10", 4, "application/vnd.symbian.install");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x7a\x1a\x20\x10", 4, "x-epoc/x-sisx-app");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"xar!", sizeof "xar!" - 1, "application/x-xar");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Cr24", sizeof "Cr24" - 1, "application/x-chrome-extension");
// FILE: /Users/awick/file-5.29/magic/Magdir/assembler
    // MISSING COMMAND: regex text/x-asm
    // MISSING COMMAND: regex text/x-asm
    // MISSING COMMAND: regex text/x-asm
    // MISSING COMMAND: regex text/x-asm
    // MISSING COMMAND: regex text/x-asm
    // MISSING COMMAND: regex text/x-asm
    // MISSING COMMAND: regex text/x-asm
// FILE: /Users/awick/file-5.29/magic/Magdir/audio
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/basic
    // MISSING COMPLEX: audio/x-adpcm
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    // MISSING COMPLEX: audio/x-dec-basic
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MThd", sizeof "MThd" - 1, "audio/midi");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"CTMF", sizeof "CTMF" - 1, "audio/x-unknown");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"SBI", sizeof "SBI" - 1, "audio/x-unknown");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Creative Voice File", sizeof "Creative Voice File" - 1, "audio/x-unknown");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x2e\x72\x61\xfd", 4, "audio/x-pn-realaudio");
    moloch_parsers_molochmagic_add(0, (uint8_t *)".RMF\0\0\0", sizeof ".RMF\0\0\0" - 1, "application/vnd.rn-realmedia");
    // MISSING COMPLEX: audio/x-mod
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Extended Module:", sizeof "Extended Module:" - 1, "audio/x-mod");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"IMPM", sizeof "IMPM" - 1, "audio/x-mod");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"fLaC", sizeof "fLaC" - 1, "audio/x-flac");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MAC\040", sizeof "MAC\040" - 1, "audio/x-ape");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MP+", sizeof "MP+" - 1, "audio/x-musepack");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MPCK", sizeof "MPCK" - 1, "audio/x-musepack");
    // MISSING COMPLEX: audio/x-vpm-wav-garmin
// FILE: /Users/awick/file-5.29/magic/Magdir/bioinformatics
    // MISSING COMPLEX: application/x-gzip
// FILE: /Users/awick/file-5.29/magic/Magdir/c-lang
    moloch_parsers_molochmagic_add_search((uint8_t *)"\"libhdr\"", sizeof "\"libhdr\"" - 1, "text/x-bcpl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\"LIBHDR\"", sizeof "\"LIBHDR\"" - 1, "text/x-bcpl");
    // MISSING COMMAND: regex text/x-c
    // MISSING COMMAND: regex text/x-c
    // MISSING COMMAND: regex text/x-c
    // MISSING COMMAND: regex text/x-c
    // MISSING COMMAND: regex text/x-c
    // MISSING COMMAND: regex text/x-c
    // MISSING COMMAND: regex text/x-c
    moloch_parsers_molochmagic_add_search((uint8_t *)"main(", sizeof "main(" - 1, "text/x-c");
    // MISSING COMMAND: regex text/x-c++
    // MISSING COMMAND: regex text/x-c++
    // MISSING COMMAND: regex text/x-c++
    // MISSING COMMAND: regex text/x-c++
    // MISSING COMMAND: regex text/x-c++
    // MISSING COMMAND: regex text/x-objective-c
// FILE: /Users/awick/file-5.29/magic/Magdir/cad
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MC0.0", sizeof "MC0.0" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1.2", sizeof "AC1.2" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1.3", sizeof "AC1.3" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1.40", sizeof "AC1.40" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1.50", sizeof "AC1.50" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC2.10", sizeof "AC2.10" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC2.21", sizeof "AC2.21" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC2.22", sizeof "AC2.22" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1001", sizeof "AC1001" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1002", sizeof "AC1002" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1003", sizeof "AC1003" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1004", sizeof "AC1004" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1006", sizeof "AC1006" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1009", sizeof "AC1009" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1012", sizeof "AC1012" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1014", sizeof "AC1014" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1015", sizeof "AC1015" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1018", sizeof "AC1018" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1021", sizeof "AC1021" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1024", sizeof "AC1024" - 1, "image/vnd.dwg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"AC1027", sizeof "AC1027" - 1, "image/vnd.dwg");
// FILE: /Users/awick/file-5.29/magic/Magdir/cafebabe
    // MISSING COMPLEX: application/x-java-applet
    // MISSING COMPLEX: application/x-java-pack200
    // MISSING COMPLEX: application/x-java-pack200
    // MISSING COMPLEX: application/x-mach-binary
    // MISSING COMPLEX: application/x-mach-binary
// FILE: /Users/awick/file-5.29/magic/Magdir/cbor
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\331\331\367", sizeof "\331\331\367" - 1, "application/cbor");
// FILE: /Users/awick/file-5.29/magic/Magdir/commands
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/sh", sizeof "#! /bin/sh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/sh", sizeof "#! /bin/sh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/csh", sizeof "#! /bin/csh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/ksh", sizeof "#! /bin/ksh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/ksh", sizeof "#! /bin/ksh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/tcsh", sizeof "#! /bin/tcsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/tcsh", sizeof "#! /usr/bin/tcsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/tcsh", sizeof "#! /usr/local/tcsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/tcsh", sizeof "#! /usr/local/bin/tcsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/zsh", sizeof "#! /bin/zsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/zsh", sizeof "#! /usr/bin/zsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/zsh", sizeof "#! /usr/local/bin/zsh" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/ash", sizeof "#! /usr/local/bin/ash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/ae", sizeof "#! /usr/local/bin/ae" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/nawk", sizeof "#! /bin/nawk" - 1, "text/x-nawk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/nawk", sizeof "#! /usr/bin/nawk" - 1, "text/x-nawk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/nawk", sizeof "#! /usr/local/bin/nawk" - 1, "text/x-nawk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/gawk", sizeof "#! /bin/gawk" - 1, "text/x-gawk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/gawk", sizeof "#! /usr/bin/gawk" - 1, "text/x-gawk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/gawk", sizeof "#! /usr/local/bin/gawk" - 1, "text/x-gawk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/awk", sizeof "#! /bin/awk" - 1, "text/x-awk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/awk", sizeof "#! /usr/bin/awk" - 1, "text/x-awk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/bash", sizeof "#! /bin/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /bin/bash", sizeof "#! /bin/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/bash", sizeof "#! /usr/bin/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/bash", sizeof "#! /usr/bin/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bash", sizeof "#! /usr/local/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bash", sizeof "#! /usr/local/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/bash", sizeof "#! /usr/local/bin/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/bash", sizeof "#! /usr/local/bin/bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/env bash", sizeof "#! /usr/bin/env bash" - 1, "text/x-shellscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?php", sizeof "<?php" - 1, "text/x-php");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?\n", sizeof "<?\n" - 1, "text/x-php");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?\r", sizeof "<?\r" - 1, "text/x-php");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/php", sizeof "#! /usr/local/bin/php" - 1, "text/x-php");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/php", sizeof "#! /usr/bin/php" - 1, "text/x-php");
    // MISSING COMPLEX: text/x-php
// FILE: /Users/awick/file-5.29/magic/Magdir/compress
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\037\235", sizeof "\037\235" - 1, "application/x-compress");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\037\213", sizeof "\037\213" - 1, "application/x-gzip");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\037\036", sizeof "\037\036" - 1, "application/octet-stream");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x1f\x1f", 2, "application/octet-stream");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xff\x1f", 2, "application/octet-stream");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\377\037", sizeof "\377\037" - 1, "application/octet-stream");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x05\xcb", 2, "application/octet-stream");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"BZh", sizeof "BZh" - 1, "application/x-bzip2");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"LZIP", sizeof "LZIP" - 1, "application/x-lzip");
    // MISSING COMPLEX: application/x-7z-compressed
    // MISSING COMPLEX: application/x-lzma
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\3757zXZ\000", sizeof "\3757zXZ\000" - 1, "application/x-xz");
    // MISSING COMPLEX: application/x-lrzip
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x04\x22\x4d\x18", 4, "application/x-lz4");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x03\x21\x4c\x18", 4, "application/x-lz4");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x02\x21\x4c\x18", 4, "application/x-lz4");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x22\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x23\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x24\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x25\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x26\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x27\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x28\xb5\x2f\xfd", 4, "application/x-zstd");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x37\xa4\x30\xec", 4, "application/x-zstd-dictionary");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\377\006\0\0sNaPpY", sizeof "\377\006\0\0sNaPpY" - 1, "application/x-snappy-framed");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"qpress10", sizeof "qpress10" - 1, "application/x-qpress");
    // MISSING COMPLEX: application/zlib
// FILE: /Users/awick/file-5.29/magic/Magdir/cups
    // MISSING COMPLEX: application/vnd.cups-raster
    // MISSING COMPLEX: application/vnd.cups-raster
// FILE: /Users/awick/file-5.29/magic/Magdir/database
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x13\x57\x9a\xcd", 4, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x13\x57\x9a\xce", 4, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x13\x57\x9a\xcf", 4, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xcd\x9a\x57\x13", 4, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xce\x9a\x57\x13", 4, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xcf\x9a\x57\x13", 4, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"GDBM", sizeof "GDBM" - 1, "application/x-gdbm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x61\x15\x06\x00", 4, "application/x-dbm");
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbf
    // MISSING COMPLEX: application/x-dbt
    moloch_parsers_molochmagic_add(4, (uint8_t *)"Standard Jet DB", sizeof "Standard Jet DB" - 1, "application/x-msaccess");
    moloch_parsers_molochmagic_add(4, (uint8_t *)"Standard ACE DB", sizeof "Standard ACE DB" - 1, "application/x-msaccess");
    // MISSING COMPLEX: application/x-ms-ese
    // MISSING COMPLEX: application/x-ms-sdb
    // MISSING COMPLEX: application/x-tokyocabinet-hash
    // MISSING COMPLEX: application/x-tokyocabinet-btree
    // MISSING COMPLEX: application/x-tokyocabinet-fixed
    // MISSING COMPLEX: application/x-tokyocabinet-table
// FILE: /Users/awick/file-5.29/magic/Magdir/diff
    moloch_parsers_molochmagic_add(0, (uint8_t *)"diff ", sizeof "diff " - 1, "text/x-diff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"*** ", sizeof "*** " - 1, "text/x-diff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Only in ", sizeof "Only in " - 1, "text/x-diff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Common subdirectories: ", sizeof "Common subdirectories: " - 1, "text/x-diff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Index:", sizeof "Index:" - 1, "text/x-diff");
    // MISSING COMPLEX: text/x-diff
// FILE: /Users/awick/file-5.29/magic/Magdir/dolby
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x0b\x77", 2, "audio/vnd.dolby.dd-raw");
// FILE: /Users/awick/file-5.29/magic/Magdir/elf
    // MISSING COMPLEX: application/octet-stream
    // MISSING COMPLEX: application/x-object
    // MISSING COMPLEX: application/x-executable
    // MISSING COMPLEX: application/x-sharedlib
    // MISSING COMPLEX: application/x-coredump
// FILE: /Users/awick/file-5.29/magic/Magdir/epoc
    // MISSING COMPLEX: image/x-epoc-mbm
    // MISSING COMPLEX: image/x-epoc-sketch
    // MISSING COMPLEX: application/x-epoc-word
    // MISSING COMPLEX: application/x-epoc-opl
    // MISSING COMPLEX: application/x-epoc-sheet
    // MISSING COMPLEX: application/x-epoc-opo
    // MISSING COMPLEX: application/x-epoc-app
    // MISSING COMPLEX: application/x-epoc-agenda
    // MISSING COMPLEX: application/x-epoc-data
    // MISSING COMPLEX: application/x-epoc-jotter
// FILE: /Users/awick/file-5.29/magic/Magdir/filesystems
    // MISSING COMPLEX: application/x-ima
    // MISSING COMPLEX: application/x-iso9660-image
    // MISSING COMPLEX: application/x-iso9660-image
// FILE: /Users/awick/file-5.29/magic/Magdir/flash
    // MISSING COMPLEX: application/x-shockwave-flash
    // MISSING COMPLEX: application/x-shockwave-flash
    // MISSING COMPLEX: application/x-shockwave-flash
    moloch_parsers_molochmagic_add(0, (uint8_t *)"FLV\001", sizeof "FLV\001" - 1, "video/x-flv");
// FILE: /Users/awick/file-5.29/magic/Magdir/fonts
    // MISSING COMPLEX: application/x-font-pfm
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x00\x00\x00\x04", 4, "application/x-font-sfn");
    // MISSING COMPLEX: application/x-font-sfn
    // MISSING COMPLEX: application/x-font-pf2
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\000\001\000\000\000", sizeof "\000\001\000\000\000" - 1, "application/x-font-ttf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"OTTO", sizeof "OTTO" - 1, "application/vnd.ms-opentype");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"SplineFontDB:", sizeof "SplineFontDB:" - 1, "application/vnd.font-fontforge-sfd");
    // MISSING COMPLEX: application/vnd.ms-fontobject
// FILE: /Users/awick/file-5.29/magic/Magdir/fortran
    // MISSING COMPLEX: text/x-fortran
// FILE: /Users/awick/file-5.29/magic/Magdir/frame
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<MakerFile", sizeof "<MakerFile" - 1, "application/x-mif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<MIFFile", sizeof "<MIFFile" - 1, "application/x-mif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<MakerDictionary", sizeof "<MakerDictionary" - 1, "application/x-mif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<MakerScreenFont", sizeof "<MakerScreenFont" - 1, "application/x-mif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<MML", sizeof "<MML" - 1, "application/x-mif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<BookFile", sizeof "<BookFile" - 1, "application/x-mif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<Maker\040Intermediate\040Print\040File", sizeof "<Maker\040Intermediate\040Print\040File" - 1, "application/x-mif");
// FILE: /Users/awick/file-5.29/magic/Magdir/gimp
    moloch_parsers_molochmagic_add(0, (uint8_t *)"gimp xcf", sizeof "gimp xcf" - 1, "image/x-xcf");
// FILE: /Users/awick/file-5.29/magic/Magdir/gnu
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x85\x02", 2, "text/PGP");
    // MISSING COMPLEX: application/x-gnupg-keyring
    // MISSING COMPLEX: text/x-po
// FILE: /Users/awick/file-5.29/magic/Magdir/gnumeric
// FILE: /Users/awick/file-5.29/magic/Magdir/icc
// FILE: /Users/awick/file-5.29/magic/Magdir/iff
    // MISSING COMPLEX: audio/x-aiff
    // MISSING COMPLEX: audio/x-aiff
    // MISSING COMPLEX: audio/x-aiff
    // MISSING COMPLEX: application/x-blorb
// FILE: /Users/awick/file-5.29/magic/Magdir/images
    // MISSING COMPLEX: image/x-tga
    // MISSING COMPLEX: image/x-portable-bitmap
    // MISSING COMPLEX: image/x-portable-greymap
    // MISSING COMPLEX: image/x-portable-pixmap
    // MISSING COMPLEX: image/x-portable-bitmap
    // MISSING COMPLEX: image/x-portable-greymap
    // MISSING COMPLEX: image/x-portable-pixmap
    moloch_parsers_molochmagic_add(0, (uint8_t *)"P7", sizeof "P7" - 1, "image/x-portable-pixmap");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"IIN1", sizeof "IIN1" - 1, "image/x-niff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"II\032\0\0\0HEAPCCDR", sizeof "II\032\0\0\0HEAPCCDR" - 1, "image/x-canon-crw");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"II\052\0\020\0\0\0CR", sizeof "II\052\0\020\0\0\0CR" - 1, "image/x-canon-cr2");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MM\000\052", sizeof "MM\000\052" - 1, "image/tiff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"II\052\000", sizeof "II\052\000" - 1, "image/tiff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MM\000\053", sizeof "MM\000\053" - 1, "image/tiff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"II\053\000", sizeof "II\053\000" - 1, "image/tiff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\211PNG\015\012\032\012", sizeof "\211PNG\015\012\032\012" - 1, "image/png");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"GIF94z", sizeof "GIF94z" - 1, "image/x-unknown");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"FGF95a", sizeof "FGF95a" - 1, "image/x-unknown");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"PBF", sizeof "PBF" - 1, "image/x-unknown");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"GIF8", sizeof "GIF8" - 1, "image/gif");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\021\006", sizeof "\021\006" - 1, "image/x-award-bioslogo");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\021\011", sizeof "\021\011" - 1, "image/x-award-bioslogo");
    // MISSING COMPLEX: image/x-award-bmp
    // MISSING COMPLEX: image/x-ms-bmp
    // MISSING COMPLEX: image/x-ms-bmp
    // MISSING COMPLEX: image/x-ms-bmp
    // MISSING COMPLEX: image/x-ms-bmp
    // MISSING COMPLEX: image/x-ms-bmp
    // MISSING COMPLEX: image/x-ms-bmp
    moloch_parsers_molochmagic_add(0, (uint8_t *)"/* XPM */", sizeof "/* XPM */" - 1, "image/x-xpmi");
    // MISSING COMPLEX: image/x-xwindowdump
    // MISSING COMPLEX: image/x-pcx
    moloch_parsers_molochmagic_add(0, (uint8_t *)"8BPS", sizeof "8BPS" - 1, "image/vnd.adobe.photoshop");
    // MISSING COMPLEX: image/x-gem
    // MISSING COMPLEX: image/vnd.djvu
    // MISSING COMPLEX: image/vnd.djvu
    // MISSING COMPLEX: image/vnd.djvu
    // MISSING COMPLEX: image/vnd.djvu
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x76\x2f\x31\x01", 4, "image/x-exr");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"SDPX", sizeof "SDPX" - 1, "image/x-dpx");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x0e\x03\x13\x01", 4, "application/x-hdf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\211HDF\r\n\032\n", sizeof "\211HDF\r\n\032\n" - 1, "application/x-hdf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"CPC\262", sizeof "CPC\262" - 1, "image/x-cpi");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"[BitmapInfo2]", sizeof "[BitmapInfo2]" - 1, "image/x-polar-monitor-bitmap");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MMOR", sizeof "MMOR" - 1, "image/x-olympus-orf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"IIRO", sizeof "IIRO" - 1, "image/x-olympus-orf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"IIRS", sizeof "IIRS" - 1, "image/x-olympus-orf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"FOVb", sizeof "FOVb" - 1, "image/x-x3f");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"PDN3", sizeof "PDN3" - 1, "image/x-paintnet");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\102\120\107\373", sizeof "\102\120\107\373" - 1, "image/bpg");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"icns", sizeof "icns" - 1, "image/x-icns");
// FILE: /Users/awick/file-5.29/magic/Magdir/intel
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x55\xaa", 2, "application/octet-stream");
// FILE: /Users/awick/file-5.29/magic/Magdir/java
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xfe\xed\xfe\xed", 4, "application/x-java-keystore");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xce\xce\xce\xce", 4, "application/x-java-jce-keystore");
    // MISSING COMMAND: regex text/x-java
// FILE: /Users/awick/file-5.29/magic/Magdir/javascript
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/bin/node", sizeof "#!/bin/node" - 1, "application/javascript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/node", sizeof "#!/usr/bin/node" - 1, "application/javascript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/bin/nodejs", sizeof "#!/bin/nodejs" - 1, "application/javascript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/nodejs", sizeof "#!/usr/bin/nodejs" - 1, "application/javascript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env node", sizeof "#!/usr/bin/env node" - 1, "application/javascript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env nodejs", sizeof "#!/usr/bin/env nodejs" - 1, "application/javascript");
// FILE: /Users/awick/file-5.29/magic/Magdir/jpeg
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xff\xd8", 2, "image/jpeg");
    // MISSING COMPLEX: image/jp2
    // MISSING COMPLEX: image/jpx
    // MISSING COMPLEX: image/jpm
    // MISSING COMPLEX: video/mj2
    // MISSING COMPLEX: image/jxr
// FILE: /Users/awick/file-5.29/magic/Magdir/kde
    moloch_parsers_molochmagic_add(0, (uint8_t *)"[KDE Desktop Entry]", sizeof "[KDE Desktop Entry]" - 1, "application/x-kdelnk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"# KDE Config File", sizeof "# KDE Config File" - 1, "application/x-kdelnk");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"# xmcd", sizeof "# xmcd" - 1, "text/x-xmcd");
// FILE: /Users/awick/file-5.29/magic/Magdir/kml
    // MISSING COMPLEX: application/vnd.google-earth.kml+xml
    // MISSING COMPLEX: application/vnd.google-earth.kml+xml
    // MISSING COMPLEX: application/vnd.google-earth.kmz
// FILE: /Users/awick/file-5.29/magic/Magdir/linux
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x3d\xf3\x13\x14", 4, "image/x-lss16");
    // MISSING COMPLEX: application/octet-stream
// FILE: /Users/awick/file-5.29/magic/Magdir/lisp
    moloch_parsers_molochmagic_add_search((uint8_t *)"(setq ", sizeof "(setq " - 1, "text/x-lisp");
    moloch_parsers_molochmagic_add_search((uint8_t *)"(defvar ", sizeof "(defvar " - 1, "text/x-lisp");
    moloch_parsers_molochmagic_add_search((uint8_t *)"(defparam ", sizeof "(defparam " - 1, "text/x-lisp");
    moloch_parsers_molochmagic_add_search((uint8_t *)"(defun ", sizeof "(defun " - 1, "text/x-lisp");
    moloch_parsers_molochmagic_add_search((uint8_t *)"(autoload ", sizeof "(autoload " - 1, "text/x-lisp");
    moloch_parsers_molochmagic_add_search((uint8_t *)"(custom-set-variables ", sizeof "(custom-set-variables " - 1, "text/x-lisp");
    // MISSING COMPLEX: application/x-elc
    // MISSING COMPLEX: application/x-elc
    // MISSING COMPLEX: application/x-elc		
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<TeXmacs|", sizeof "<TeXmacs|" - 1, "text/texmacs");
// FILE: /Users/awick/file-5.29/magic/Magdir/lua
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/lua", sizeof "#! /usr/bin/lua" - 1, "text/x-lua");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/lua", sizeof "#! /usr/local/bin/lua" - 1, "text/x-lua");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env lua", sizeof "#!/usr/bin/env lua" - 1, "text/x-lua");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/env lua", sizeof "#! /usr/bin/env lua" - 1, "text/x-lua");
// FILE: /Users/awick/file-5.29/magic/Magdir/m4
    // MISSING COMMAND: regex text/x-m4
// FILE: /Users/awick/file-5.29/magic/Magdir/mach
    // MISSING COMMAND: lelong&0xfffffffe application/x-mach-binary
    // MISSING COMMAND: belong&0xfffffffe application/x-mach-binary
// FILE: /Users/awick/file-5.29/magic/Magdir/macintosh
    moloch_parsers_molochmagic_add(11, (uint8_t *)"must be converted with BinHex", sizeof "must be converted with BinHex" - 1, "application/mac-binhex40");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"SIT!", sizeof "SIT!" - 1, "application/x-stuffit");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"StuffIt", sizeof "StuffIt" - 1, "application/x-stuffit");
    // MISSING COMPLEX: application/x-apple-diskimage
// FILE: /Users/awick/file-5.29/magic/Magdir/mail.news
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Relay-Version:", sizeof "Relay-Version:" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! rnews", sizeof "#! rnews" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"N#! rnews", sizeof "N#! rnews" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Forward to", sizeof "Forward to" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Pipe to", sizeof "Pipe to" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"delivered-to:", sizeof "delivered-to:" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"return-path:", sizeof "return-path:" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Path:", sizeof "Path:" - 1, "message/news");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Xref:", sizeof "Xref:" - 1, "message/news");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"From:", sizeof "From:" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Article", sizeof "Article" - 1, "message/news");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Received:", sizeof "Received:" - 1, "message/rfc822");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x78\x9f\x3e\x22", 4, "application/vnd.ms-tnef");
// FILE: /Users/awick/file-5.29/magic/Magdir/make
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
    // MISSING COMMAND: regex/100l text/x-makefile
// FILE: /Users/awick/file-5.29/magic/Magdir/marc21
    // MISSING COMPLEX: application/marc
    // MISSING COMPLEX: application/marc
    // MISSING COMPLEX: application/marc
    // MISSING COMMAND: regex/1l application/marc
    // MISSING COMPLEX: application/marc
    // MISSING COMPLEX: application/marc
// FILE: /Users/awick/file-5.29/magic/Magdir/matroska
    // MISSING COMPLEX: video/webm
    // MISSING COMPLEX: video/x-matroska
// FILE: /Users/awick/file-5.29/magic/Magdir/meteorological
    // MISSING COMPLEX: rinex/broadcast
    // MISSING COMPLEX: rinex/observation
    // MISSING COMPLEX: rinex/clock
    // MISSING COMPLEX: rinex/navigation
    // MISSING COMPLEX: rinex/navigation
    // MISSING COMPLEX: rinex/navigation
    // MISSING COMPLEX: rinex/meteorological
    // MISSING COMPLEX: rinex/navigation
    // MISSING COMPLEX: rinex/observation
// FILE: /Users/awick/file-5.29/magic/Magdir/microfocus
    // MISSING COMPLEX: application/octet-stream
    // MISSING COMPLEX: application/octet-stream
    // MISSING COMPLEX: application/octet-stream
// FILE: /Users/awick/file-5.29/magic/Magdir/misctools
    moloch_parsers_molochmagic_add(0, (uint8_t *)"BEGIN:VCALENDAR", sizeof "BEGIN:VCALENDAR" - 1, "text/calendar");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"BEGIN:VCARD", sizeof "BEGIN:VCARD" - 1, "text/vcard");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MDMP", sizeof "MDMP" - 1, "application/x-dmp");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#\040abook\040addressbook\040file", sizeof "#\040abook\040addressbook\040file" - 1, "application/x-abook-addressbook");
// FILE: /Users/awick/file-5.29/magic/Magdir/modem
    // MISSING COMPLEX: image/g3fax
    // MISSING COMPLEX: image/g3fax
// FILE: /Users/awick/file-5.29/magic/Magdir/msdos
    // MISSING COMPLEX: text/x-msdos-batch
    // MISSING COMPLEX: text/x-msdos-batch
    // MISSING COMPLEX: text/x-msdos-batch
    // MISSING COMPLEX: text/x-msdos-batch
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/zip6
    // MISSING COMPLEX: application/zip7
    // MISSING COMPLEX: application/x-lha
    // MISSING COMPLEX: application/x-lha
    // MISSING COMPLEX: application/x-dosexec
    // MISSING COMPLEX: application/x-c32-comboot-syslinux-exec
    // MISSING COMPLEX: application/x-dosexec
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x31\xbe\x00\x00", 4, "application/msword");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"PO^Q`", sizeof "PO^Q`" - 1, "application/msword");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\376\067\0\043", sizeof "\376\067\0\043" - 1, "application/msword");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\333\245-\0\0\0", sizeof "\333\245-\0\0\0" - 1, "application/msword");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\333\245\055\000", sizeof "\333\245\055\000" - 1, "application/msword");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\333\245\055\000", sizeof "\333\245\055\000" - 1, "application/msword");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\011\004\006\000\000\000\020\000", sizeof "\011\004\006\000\000\000\020\000" - 1, "application/vnd.ms-excel");
    // MISSING COMPLEX: application/vnd.lotus-1-2-3
    // MISSING COMPLEX: application/vnd.lotus-1-2-3
    moloch_parsers_molochmagic_add(0, (uint8_t *)"WordPro\0", sizeof "WordPro\0" - 1, "application/vnd.lotus-wordpro");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"WordPro\r\373", sizeof "WordPro\r\373" - 1, "application/vnd.lotus-wordpro");
    // MISSING COMPLEX: image/x-icon
    // MISSING COMPLEX: image/x-win-bitmap
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x78\x9f", 2, "application/vnd.ms-tnef");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"MSCF\0\0\0\0", sizeof "MSCF\0\0\0\0" - 1, "application/vnd.ms-cab-compressed");
    // MISSING COMPLEX: application/msword
    // MISSING COMPLEX: application/msword
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\224\246\056", sizeof "\224\246\056" - 1, "application/msword");
    // MISSING COMPLEX: application/x-ms-reader
// FILE: /Users/awick/file-5.29/magic/Magdir/msooxml
    // MISSING COMPLEX: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    // MISSING COMPLEX: application/vnd.openxmlformats-officedocument.presentationml.presentation
    // MISSING COMPLEX: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
// FILE: /Users/awick/file-5.29/magic/Magdir/msvc
    // MISSING COMPLEX: application/x-ms-pdb
// FILE: /Users/awick/file-5.29/magic/Magdir/neko
    // MISSING COMPLEX: application/x-nekovm-bytecode
// FILE: /Users/awick/file-5.29/magic/Magdir/pascal
    moloch_parsers_molochmagic_add_search((uint8_t *)"(input,", sizeof "(input," - 1, "text/x-pascal");
// FILE: /Users/awick/file-5.29/magic/Magdir/pdf
    moloch_parsers_molochmagic_add(0, (uint8_t *)"%PDF-", sizeof "%PDF-" - 1, "application/pdf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\012%PDF-", sizeof "\012%PDF-" - 1, "application/pdf");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"%FDF-", sizeof "%FDF-" - 1, "application/vnd.fdf");
// FILE: /Users/awick/file-5.29/magic/Magdir/perl
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval \"exec perl", sizeof "eval \"exec perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval \"exec /bin/perl", sizeof "eval \"exec /bin/perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval \"exec /usr/bin/perl", sizeof "eval \"exec /usr/bin/perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval \"exec /usr/local/bin/perl", sizeof "eval \"exec /usr/local/bin/perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval 'exec perl", sizeof "eval 'exec perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval 'exec /bin/perl", sizeof "eval 'exec /bin/perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval 'exec /usr/bin/perl", sizeof "eval 'exec /usr/bin/perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval 'exec /usr/local/bin/perl", sizeof "eval 'exec /usr/local/bin/perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add_search((uint8_t *)"eval '(exit $?0)' && eval 'exec", sizeof "eval '(exit $?0)' && eval 'exec" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env perl", sizeof "#!/usr/bin/env perl" - 1, "text/x-perl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/env perl", sizeof "#! /usr/bin/env perl" - 1, "text/x-perl");
    // MISSING COMPLEX: text/x-perl
// FILE: /Users/awick/file-5.29/magic/Magdir/pgf
    moloch_parsers_molochmagic_add(0, (uint8_t *)"PGF", sizeof "PGF" - 1, "image/x-pgf");
// FILE: /Users/awick/file-5.29/magic/Magdir/pgp
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x99\x00", 2, "application/x-pgp-keyring");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x95\x01", 2, "application/x-pgp-keyring");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\x95\x00", 2, "application/x-pgp-keyring");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xa6\x00", 2, "text/PGP");
    moloch_parsers_molochmagic_add(2, (uint8_t *)"---BEGIN PGP PUBLIC KEY BLOCK-", sizeof "---BEGIN PGP PUBLIC KEY BLOCK-" - 1, "application/pgp-keys");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"-----BEGIN\040PGP\40MESSAGE-", sizeof "-----BEGIN\040PGP\40MESSAGE-" - 1, "application/pgp");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"-----BEGIN\040PGP\40SIGNATURE-", sizeof "-----BEGIN\040PGP\40SIGNATURE-" - 1, "application/pgp-signature");
// FILE: /Users/awick/file-5.29/magic/Magdir/pkgadd
    moloch_parsers_molochmagic_add(0, (uint8_t *)"# PaCkAgE DaTaStReAm", sizeof "# PaCkAgE DaTaStReAm" - 1, "application/x-svr4-package");
// FILE: /Users/awick/file-5.29/magic/Magdir/printer
    moloch_parsers_molochmagic_add(0, (uint8_t *)"%!", sizeof "%!" - 1, "application/postscript");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\004%!", sizeof "\004%!" - 1, "application/postscript");
// FILE: /Users/awick/file-5.29/magic/Magdir/python
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/python", sizeof "#! /usr/bin/python" - 1, "text/x-python");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/python", sizeof "#! /usr/local/bin/python" - 1, "text/x-python");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env python", sizeof "#!/usr/bin/env python" - 1, "text/x-python");
    moloch_parsers_molochmagic_add_search((uint8_t *)"#! /usr/bin/env python", sizeof "#! /usr/bin/env python" - 1, "text/x-python");
    // MISSING COMMAND: regex text/x-python
    // MISSING COMPLEX: text/x-python
    // MISSING COMPLEX: text/x-python
    // MISSING COMPLEX: text/x-python
    // MISSING COMPLEX: text/x-python
// FILE: /Users/awick/file-5.29/magic/Magdir/riff
    // MISSING COMPLEX: audio/x-wav
    // MISSING COMPLEX: image/x-coreldraw
    // MISSING COMPLEX: image/x-coreldraw
    // MISSING COMPLEX: video/x-msvideo
    // MISSING COMPLEX: image/webp
    // MISSING COMPLEX: audio/x-w64
    moloch_parsers_molochmagic_add(0, (uint8_t *)"RF64\377\377\377\377WAVEds64", sizeof "RF64\377\377\377\377WAVEds64" - 1, "audio/x-wav");
// FILE: /Users/awick/file-5.29/magic/Magdir/rpm
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xed\xab\xee\xdb", 4, "application/x-rpm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"drpm", sizeof "drpm" - 1, "application/x-rpm");
// FILE: /Users/awick/file-5.29/magic/Magdir/rtf
    moloch_parsers_molochmagic_add(0, (uint8_t *)"{\\rtf", sizeof "{\\rtf" - 1, "text/rtf");
// FILE: /Users/awick/file-5.29/magic/Magdir/ruby
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/ruby", sizeof "#! /usr/bin/ruby" - 1, "text/x-ruby");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/ruby", sizeof "#! /usr/local/bin/ruby" - 1, "text/x-ruby");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env ruby", sizeof "#!/usr/bin/env ruby" - 1, "text/x-ruby");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/env ruby", sizeof "#! /usr/bin/env ruby" - 1, "text/x-ruby");
    // MISSING COMPLEX: text/x-ruby
    // MISSING COMPLEX: text/x-ruby
// FILE: /Users/awick/file-5.29/magic/Magdir/sc
// FILE: /Users/awick/file-5.29/magic/Magdir/scientific
    // MISSING COMPLEX: chemical/x-pdb
// FILE: /Users/awick/file-5.29/magic/Magdir/sereal
    moloch_parsers_molochmagic_add(0, (uint8_t *)"srl", sizeof "srl" - 1, "application/sereal");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\363rl", sizeof "\363rl" - 1, "application/sereal");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\303\263rl", sizeof "\303\263rl" - 1, "application/sereal");
// FILE: /Users/awick/file-5.29/magic/Magdir/sgml
    // MISSING COMPLEX: image/svg+xml
    // MISSING COMPLEX: application/x-gnucash
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<svg", sizeof "<svg" - 1, "image/svg");
    // MISSING COMPLEX: application/xml-sitemap
    // MISSING COMPLEX: text/html
    // MISSING COMPLEX: text/html
    // MISSING COMPLEX: text/html
    moloch_parsers_molochmagic_add_search((uint8_t *)"<!doctype html", sizeof "<!doctype html" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<head>", sizeof "<head>" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<head ", sizeof "<head " - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<title>", sizeof "<title>" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<title ", sizeof "<title " - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<html>", sizeof "<html>" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<html ", sizeof "<html " - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<script>", sizeof "<script>" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<script ", sizeof "<script " - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<style>", sizeof "<style>" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<style ", sizeof "<style " - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<table>", sizeof "<table>" - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<table ", sizeof "<table " - 1, "text/html");
    moloch_parsers_molochmagic_add_search((uint8_t *)"<a href=", sizeof "<a href=" - 1, "text/html");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?xml", sizeof "<?xml" - 1, "text/xml");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?xml version \"", sizeof "<?xml version \"" - 1, "text/xml");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?xml version=\"", sizeof "<?xml version=\"" - 1, "text/xml");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?xml version='", sizeof "<?xml version='" - 1, "text/xml");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<?XML", sizeof "<?XML" - 1, "text/xml");
// FILE: /Users/awick/file-5.29/magic/Magdir/sniffer
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xa1\xb2\xc3\xd4", 4, "application/vnd.tcpdump.pcap");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\xd4\xc3\xb2\xa1", 4, "application/vnd.tcpdump.pcap");
// FILE: /Users/awick/file-5.29/magic/Magdir/sql
    moloch_parsers_molochmagic_add(0, (uint8_t *)"SQLite format 3", sizeof "SQLite format 3" - 1, "application/x-sqlite3");
// FILE: /Users/awick/file-5.29/magic/Magdir/tcl
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/tcl", sizeof "#! /usr/bin/tcl" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/tcl", sizeof "#! /usr/local/bin/tcl" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env tcl", sizeof "#!/usr/bin/env tcl" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/env tcl", sizeof "#! /usr/bin/env tcl" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/wish", sizeof "#! /usr/bin/wish" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/local/bin/wish", sizeof "#! /usr/local/bin/wish" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#!/usr/bin/env wish", sizeof "#!/usr/bin/env wish" - 1, "text/x-tcl");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"#! /usr/bin/env wish", sizeof "#! /usr/bin/env wish" - 1, "text/x-tcl");
// FILE: /Users/awick/file-5.29/magic/Magdir/terminfo
    // MISSING COMPLEX: application/x-terminfo
// FILE: /Users/awick/file-5.29/magic/Magdir/tex
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\367\002", sizeof "\367\002" - 1, "application/x-dvi");
    moloch_parsers_molochmagic_add(2, (uint8_t *)"\000\021", sizeof "\000\021" - 1, "application/x-tex-tfm");
    moloch_parsers_molochmagic_add(2, (uint8_t *)"\000\022", sizeof "\000\022" - 1, "application/x-tex-tfm");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\\input texinfo", sizeof "\\input texinfo" - 1, "text/x-texinfo");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"This is Info file", sizeof "This is Info file" - 1, "text/x-info");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\input", sizeof "\\input" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\begin", sizeof "\\begin" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\section", sizeof "\\section" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\setlength", sizeof "\\setlength" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\documentstyle", sizeof "\\documentstyle" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\chapter", sizeof "\\chapter" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\documentclass", sizeof "\\documentclass" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\relax", sizeof "\\relax" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"\\contentsline", sizeof "\\contentsline" - 1, "text/x-tex");
    moloch_parsers_molochmagic_add_search((uint8_t *)"% -*-latex-*-", sizeof "% -*-latex-*-" - 1, "text/x-tex");
// FILE: /Users/awick/file-5.29/magic/Magdir/troff
    moloch_parsers_molochmagic_add(0, (uint8_t *)".\\\"", sizeof ".\\\"" - 1, "text/troff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"'\\\"", sizeof "'\\\"" - 1, "text/troff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"'.\\\"", sizeof "'.\\\"" - 1, "text/troff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"\\\"", sizeof "\\\"" - 1, "text/troff");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"'''", sizeof "'''" - 1, "text/troff");
    // MISSING COMMAND: regex/20l text/troff
    // MISSING COMMAND: regex/20l text/troff
// FILE: /Users/awick/file-5.29/magic/Magdir/vorbis
    // MISSING COMPLEX: audio/ogg
    // MISSING COMPLEX: video/ogg
    // MISSING COMPLEX: application/ogg
    // MISSING COMPLEX: video/ogg
    // MISSING COMPLEX: audio/ogg
    // MISSING COMPLEX: video/ogg
    // MISSING COMPLEX: audio/ogg
    // MISSING COMPLEX: audio/ogg
// FILE: /Users/awick/file-5.29/magic/Magdir/warc
    // MISSING COMPLEX: application/warc
    moloch_parsers_molochmagic_add(0, (uint8_t *)"filedesc://", sizeof "filedesc://" - 1, "application/x-ia-arc");
// FILE: /Users/awick/file-5.29/magic/Magdir/windows
    // MISSING COMPLEX: application/winhelp
    // MISSING COMPLEX: application/x-winhelp
    // MISSING COMPLEX: application/x-winhelp
    // MISSING COMPLEX: application/winhelp
    // MISSING COMPLEX: application/x-winhelp
    // MISSING COMPLEX: text/plain
    moloch_parsers_molochmagic_add(0, (uint8_t *)"tfMR", sizeof "tfMR" - 1, "application/x-winhelp-fts");
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-setupscript
    // MISSING COMPLEX: application/x-setupscript
    // MISSING COMPLEX: text/inf
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-wine-extension-ini
    // MISSING COMPLEX: application/x-setupscript
    // MISSING COMPLEX: application/x-setupscript
    // MISSING COMPLEX: application/x-setupscript
    // MISSING COMPLEX: application/x-setupscript
    // MISSING COMPLEX: application/x-pnf
// FILE: /Users/awick/file-5.29/magic/Magdir/wordprocessors
    moloch_parsers_molochmagic_add(2, (uint8_t *)"MMXPR3", sizeof "MMXPR3" - 1, "application/x-quark-xpress-3");
    // MISSING COMPLEX: application/x-ichitaro4
    // MISSING COMPLEX: application/x-ichitaro5
    // MISSING COMPLEX: application/x-ichitaro6
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<map version", sizeof "<map version" - 1, "application/x-freemind");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<map version=\"freeplane", sizeof "<map version=\"freeplane" - 1, "application/x-freeplane");
    moloch_parsers_molochmagic_add(0, (uint8_t *)"<SCRIBUSUTF8NEW Version", sizeof "<SCRIBUSUTF8NEW Version" - 1, "application/x-scribus");
// FILE: /Users/awick/file-5.29/magic/Magdir/xenix
    // MISSING COMPLEX: application/x-object
// FILE: /Users/awick/file-5.29/magic/Magdir/xwindows
    moloch_parsers_molochmagic_add(0, (uint8_t *)"Xcur", sizeof "Xcur" - 1, "image/x-xcursor");
}
