apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkime.fullname" . }}-central-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.centralViewer.replicas }}
  revisionHistoryLimit: {{ .Values.centralViewer.revisionHistoryLimit }}
  {{- with .Values.centralViewer.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkime.fullname" . }}
      app.kubernetes.io/instance: central-viewer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkime.fullname" . }}
        app.kubernetes.io/instance: central-viewer
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.centralViewer.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.centralViewer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arkime.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralViewer.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.centralViewer.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.centralViewer.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.centralViewer.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.centralViewer.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.centralViewer.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.centralViewer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: arkime-central-viewer
        image: "{{ .Values.centralViewer.image.repository }}:{{ .Values.centralViewer.image.tag }}"
        imagePullPolicy: {{ .Values.centralViewer.imagePullPolicy }}
        command:
          {{- toYaml .Values.centralViewer.command | nindent 10 }}
        env:
          - name: ARKIME__elasticsearch
            value: "{{ .Values.settings.elasticsearch }}"
        {{- toYaml .Values.centralViewer.env | nindent 10 }}
        {{- with .Values.centralViewer.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: arkime-config
          mountPath: /opt/arkime/etc/
        {{- with .Values.centralViewer.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.centralViewer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: arkime-config
        configMap:
          name: {{ include "arkime.fullname" . }}-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkime.fullname" . }}-central-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "arkime.fullname" . }}
    app.kubernetes.io/instance: central-viewer
  {{- with .Values.centralViewer.service.ports }}
  ports:
    {{- toYaml . | nindent 12 }}
  {{- end }}