{{- if .Values.selfSignedCA -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "arkime.fullname" . }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "arkime.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ include "arkime.fullname" . }}-self-signed-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "arkime.fullname" . }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "arkime.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: root-secret
{{- end -}}