# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1500"]
  end

  config.vm.define "ubuntu-12.04" do |ubuntu1204|
    ubuntu1204.vm.box = "chef/ubuntu-12.04"
  end

  config.vm.define "ubuntu-14.04" do |ubuntu1404|
    ubuntu1404.vm.box = "chef/ubuntu-14.04"
  end

  config.vm.define "centos-5" do |centos5|
    centos5.vm.box = "chef/centos-5.11"
  end

  config.vm.define "centos-6" do |centos6|
    centos6.vm.box = "chef/centos-6.6"
  end

  config.vm.define "centos-7" do |centos7|
    centos7.vm.box = "chef/centos-7.0"
  end

  config.vm.define "freebsd-9" do |freebsd9|
    freebsd9.vm.box = "chef/freebsd-9.2"
    freebsd9.ssh.shell = "sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "freebsd-10" do |freebsd10|
    freebsd10.vm.box = "chef/freebsd-10.0"
  end


  config.vm.provision "shell", path:"node.test.sh"
end
