FROM archlinux:latest
MAINTAINER Andy Wick <andy.wick@oath.com>

RUN pacman -Sy --noconfirm gcc ruby make python-pip git perl-test-differences sudo wget gawk ntop \
nodejs-lts-dubnium node-gyp npm lua geoip yara file libpcap libmaxminddb libnet lua libtool autoconf gettext automake
