#!/bin/bash
# Simple capital C Configure script for rpm/deb, like the old days

if [ "$1" == "--help" ]; then
    echo "Configure (--wise|--parliament|)  = Only 1 option can be used"
    echo "--wise         = install and start wise"
    echo "--parliament   = install and start parliament"
    echo "               = install moloch capture and viewer"
    echo "--help         = this help"
    exit 0
fi

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

ARKIME_NAME=BUILD_ARKIME_NAME
if [ "$ARKIME_NAME" == "BUILD_ARKIME_NAME" ]; then
    ARKIME_NAME=arkime
fi

ARKIME_INSTALL_DIR=BUILD_ARKIME_INSTALL_DIR
if [ "$ARKIME_INSTALL_DIR" == "BUILD_ARKIME_""INSTALL_DIR" ]; then
ARKIME_INSTALL_DIR=/opt/$ARKIME_NAME
fi

if [ "$1" == "--wise" ]; then
    if [ ! -f "$ARKIME_INSTALL_DIR/etc/wise.ini" ]; then
        sed -e "s,ARKIME_ELASTICSEARCH,${ARKIME_ELASTICSEARCH},g" -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/wise.ini.sample > $ARKIME_INSTALL_DIR/etc/wise.ini
    else
        echo "Not overwriting $ARKIME_INSTALL_DIR/etc/wise.ini, delete and run again if update required (usually not), or edit by hand"
        sleep 1
    fi

    if [ -d "/etc/systemd" ] && [ -x "/bin/systemctl" ]; then
        echo "Installing systemd start files, use systemctl"
        sed -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/arkimewise.systemd.service > /etc/systemd/system/arkimewise.service
        systemctl daemon-reload
        systemctl enable arkimewise
        systemctl start arkimewise
    else
        echo "No startup scripts created for wise"
    fi


    exit 0;
fi

if [ "$1" == "--parliament" ]; then
    if [ -d "/etc/systemd" ] && [ -x "/bin/systemctl" ]; then
        echo "Installing systemd start files, use systemctl"
        sed -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/arkimeparliament.systemd.service > /etc/systemd/system/arkimeparliament.service
        systemctl daemon-reload
        systemctl enable arkimeparliament
        systemctl start arkimeparliament
    else
        echo "No startup scripts created for parliament"
    fi

    exit 0;
fi

################################################################################
### Ask config questions
if [ -z "$ARKIME_INTERFACE" ]; then
    echo -n "Found interfaces: "
    if [ ! -f /sbin/ifconfig ]; then
        ip -o link | cut -f2 -d: | tr '\n' ' ' | sed 's/ \+/ /ig' | sed 's/ //1' | sed 's/[[:blank:]]*$//' | tr ' ' ';' | sed 's/$/\n/'
    else
        /sbin/ifconfig | grep "^[a-z]" | cut -d: -f1 | cut -d" " -f1 | paste -s -d";"
    fi
    echo -n "Semicolon ';' seperated list of interfaces to monitor [eth1] "
    read -r ARKIME_INTERFACE
fi
if [ -z "$ARKIME_INTERFACE" ]; then ARKIME_INTERFACE="eth1"; fi

ARKIME_LOCALELASTICSEARCH=not-set
until [ "$ARKIME_LOCALELASTICSEARCH" == "yes" ] || [ "$ARKIME_LOCALELASTICSEARCH" == "no" ] || [ "$ARKIME_LOCALELASTICSEARCH" == "" ]; do
    echo -n "Install Elasticsearch server locally for demo, must have at least 3G of memory, NOT recommended for production use (yes or no) [no] "
    read -r ARKIME_LOCALELASTICSEARCH
done

if [ "$ARKIME_LOCALELASTICSEARCH" == "yes" ]; then
    ARKIME_ELASTICSEARCH="http://localhost:9200"
    which java
    JAVA_VAL=$?

    if [ $JAVA_VAL -ne 0 ]; then
        echo "java command not found, make sure java is installed and in the path and run again"
    fi
else
    if [ -z "$ARKIME_ELASTICSEARCH" ]; then
        echo -n "Elasticsearch server URL [http://localhost:9200] "
        read -r ARKIME_ELASTICSEARCH
    fi
    if [ -z "$ARKIME_ELASTICSEARCH" ]; then ARKIME_ELASTICSEARCH="http://localhost:9200"; fi
fi

while [ -z "$ARKIME_PASSWORD" ]; do
    echo -n "Password to encrypt S2S and other things [no-default] "
    read -r ARKIME_PASSWORD
done
if [ -z "$ARKIME_PASSWORD" ]; then echo "Must provide a password"; exit; fi


################################################################################
echo "Arkime - Creating configuration files"
if [ ! -f "$ARKIME_INSTALL_DIR/etc/config.ini" ]; then
    echo sed -e "s/ARKIME_INTERFACE/${ARKIME_INTERFACE}/g" -e "s,ARKIME_ELASTICSEARCH,${ARKIME_ELASTICSEARCH},g" -e "s/ARKIME_PASSWORD/${ARKIME_PASSWORD}/g" -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/config.ini.sample > $ARKIME_INSTALL_DIR/etc/config.ini
    sed -e "s/ARKIME_INTERFACE/${ARKIME_INTERFACE}/g" -e "s,ARKIME_ELASTICSEARCH,${ARKIME_ELASTICSEARCH},g" -e "s/ARKIME_PASSWORD/${ARKIME_PASSWORD}/g" -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/config.ini.sample > $ARKIME_INSTALL_DIR/etc/config.ini
else
    echo "Not overwriting $ARKIME_INSTALL_DIR/etc/config.ini, delete and run again if update required (usually not), or edit by hand"
    sleep 2
fi


if [ -d "/etc/systemd" ] && [ -x "/bin/systemctl" ]; then
    echo "Installing systemd start files, use systemctl"
    sed -e "s/ARKIME_INTERFACE/${ARKIME_INTERFACE}/g" -e "s,ARKIME_ELASTICSEARCH,${ARKIME_ELASTICSEARCH},g" -e "s/ARKIME_PASSWORD/${ARKIME_PASSWORD}/g" -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/arkimecapture.systemd.service > /etc/systemd/system/arkimecapture.service
    sed -e "s/ARKIME_INTERFACE/${ARKIME_INTERFACE}/g" -e "s,ARKIME_ELASTICSEARCH,${ARKIME_ELASTICSEARCH},g" -e "s/ARKIME_PASSWORD/${ARKIME_PASSWORD}/g" -e "s,ARKIME_INSTALL_DIR,${ARKIME_INSTALL_DIR},g" < $ARKIME_INSTALL_DIR/etc/arkimeviewer.systemd.service > /etc/systemd/system/arkimeviewer.service
else
    echo "No startup scripts created for capture and viewer"
fi

################################################################################
# re-create these directories after installation so they are not part of the package manifest
CREATEDIRS="logs raw"
for CREATEDIR in $CREATEDIRS; do
    if [ ! -e $ARKIME_INSTALL_DIR/$CREATEDIR ]; then
        mkdir -m 0700 -p $ARKIME_INSTALL_DIR/$CREATEDIR && \
        chown nobody $ARKIME_INSTALL_DIR/$CREATEDIR
    fi
done

################################################################################
ARCHRPM=$(uname -m)
case $ARCHRPM in
    "x86_64")
        ARCHDEB="amd64"
        ;;
    "aarch64")
        ARCHDEB="arm64"
        ;;
esac

if [ "$ARKIME_LOCALELASTICSEARCH" == "yes" ]; then
    echo "Arkime - Downloading and installing demo OSS version of Elasticsearch"
    ES_VERSION=7.9.3
    if [ -f "/etc/redhat-release" ] || [ -f "/etc/system-release" ]; then
        yum install https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-${ES_VERSION}-${ARCHRPM}.rpm
    else
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-${ES_VERSION}-${ARCHDEB}.deb
        dpkg -i elasticsearch-oss-${ES_VERSION}-$ARCHDEB.deb
        /bin/rm -f elasticsearch-oss-${ES_VERSION}-$ARCHDEB.deb
    fi
fi

################################################################################
if [ -d "/etc/logrotate.d" ] && [ ! -f "/etc/logrotate.d/$ARKIME_NAME" ]; then
    echo "Arkime - Installing /etc/logrotate.d/$ARKIME_NAME to rotate files after 7 days"
    cat << EOF > /etc/logrotate.d/$ARKIME_NAME
$ARKIME_INSTALL_DIR/logs/capture.log
$ARKIME_INSTALL_DIR/logs/viewer.log {
    daily
    rotate 7
    notifempty
    copytruncate
}
EOF
fi

################################################################################
INTERFACES=${ARKIME_INTERFACE//;/ }
cat << EOF > $ARKIME_INSTALL_DIR/bin/moloch_config_interfaces.sh
#!/bin/sh
for interface in $INTERFACES; do
  /sbin/ethtool -G \$interface rx 4096 tx 4096 || true
  for i in rx tx sg tso ufo gso gro lro; do
      /sbin/ethtool -K \$interface \$i off || true
  done
done
EOF
chmod a+x $ARKIME_INSTALL_DIR/bin/moloch_config_interfaces.sh

################################################################################
if [ -d "/etc/security/limits.d" ] && [ ! -f "/etc/security/limits.d/99-moloch.conf" ]; then
    echo "Arkime - Installing /etc/security/limits.d/99-moloch.conf to make core and memlock unlimited"
    cat << EOF > /etc/security/limits.d/99-moloch.conf
nobody  -       core    unlimited
root    -       core    unlimited
nobody  -       memlock    unlimited
root    -       memlock    unlimited
EOF
fi

################################################################################

ARKIME_INET=not-set
until [ "$ARKIME_INET" == "yes" ] || [ "$ARKIME_INET" == "no" ] || [ "$ARKIME_INET" == "" ]; do
    echo -n "Download GEO files? You'll need a MaxMind account https://arkime.com/faq#maxmind (yes or no) [yes] "
    read -r ARKIME_INET
done

if [ "$ARKIME_INET" != "no" ]; then
    echo "Arkime - Downloading GEO files"
    $ARKIME_INSTALL_DIR/bin/moloch_update_geo.sh > /dev/null
else
    echo "Arkime - NOT downloading GEO files"
fi


################################################################################
echo ""
echo "Arkime - Configured - Now continue with step 4 in $ARKIME_INSTALL_DIR/README.txt"
echo ""
tail -n +10 $ARKIME_INSTALL_DIR/README.txt

